
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programnonassocIFXnonassocELSEleftOPERACIONASIGNACION COMA COMPARACION DESC ELSE FLOAT ID IF INT LLAVES NUMERO OPERACION PARENTESIS PRINT PRINTF PUNTOCOMA RETURN WHILEprogram : stmtsstmts_opt : stmts\n| emptystmts : stmts stmtstmts : stmtstmt : type ID PUNTOCOMAstmt : type ID ASIGNACION expr PUNTOCOMAstmt : ID ASIGNACION expr PUNTOCOMAstmt : PRINT PARENTESIS args_opt PARENTESIS PUNTOCOMAargs_opt : args_list\n| emptyargs_list : exprargs_list : args_list COMA exprstmt : IF PARENTESIS condition PARENTESIS block %prec IFXstmt : IF PARENTESIS condition PARENTESIS block ELSE blockstmt : WHILE PARENTESIS condition PARENTESIS blocktype : INTtype : FLOATblock : PARENTESIS stmts_opt PARENTESIScondition : expr COMPARACION exprexpr : expr OPERACION exprexpr : PARENTESIS expr PARENTESISexpr : IDexpr : NUMEROexpr : DESCempty :'
    
_lr_action_items = {'ID':([0,2,3,4,9,10,11,13,14,15,16,17,18,21,32,33,36,38,40,43,45,46,48,50,53,54,],[5,5,-5,12,-17,-18,-4,19,19,19,19,-6,19,19,-8,19,19,19,-7,-9,5,-14,-16,5,-19,-15,]),'PRINT':([0,2,3,11,17,32,40,43,45,46,48,50,53,54,],[6,6,-5,-4,-6,-8,-7,-9,6,-14,-16,6,-19,-15,]),'IF':([0,2,3,11,17,32,40,43,45,46,48,50,53,54,],[7,7,-5,-4,-6,-8,-7,-9,7,-14,-16,7,-19,-15,]),'WHILE':([0,2,3,11,17,32,40,43,45,46,48,50,53,54,],[8,8,-5,-4,-6,-8,-7,-9,8,-14,-16,8,-19,-15,]),'INT':([0,2,3,11,17,32,40,43,45,46,48,50,53,54,],[9,9,-5,-4,-6,-8,-7,-9,9,-14,-16,9,-19,-15,]),'FLOAT':([0,2,3,11,17,32,40,43,45,46,48,50,53,54,],[10,10,-5,-4,-6,-8,-7,-9,10,-14,-16,10,-19,-15,]),'$end':([1,2,3,11,17,32,40,43,46,48,53,54,],[0,-1,-5,-4,-6,-8,-7,-9,-14,-16,-19,-15,]),'PARENTESIS':([3,6,7,8,11,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,30,32,33,34,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,],[-5,14,15,16,-4,21,21,21,21,-6,21,-23,21,-24,-25,35,-10,-11,-12,37,39,-8,21,42,21,45,21,45,-7,-21,-22,-9,-13,-26,-14,-20,-16,53,-2,-3,45,-19,-15,]),'ASIGNACION':([5,12,],[13,18,]),'PUNTOCOMA':([12,19,20,22,23,31,35,41,42,],[17,-23,32,-24,-25,40,43,-21,-22,]),'NUMERO':([13,14,15,16,18,21,33,36,38,],[22,22,22,22,22,22,22,22,22,]),'DESC':([13,14,15,16,18,21,33,36,38,],[23,23,23,23,23,23,23,23,23,]),'OPERACION':([19,20,22,23,27,29,31,34,41,42,44,47,],[-23,33,-24,-25,33,33,33,33,-21,-22,33,33,]),'COMA':([19,22,23,25,27,41,42,44,],[-23,-24,-25,36,-12,-21,-22,-13,]),'COMPARACION':([19,22,23,29,41,42,],[-23,-24,-25,38,-21,-22,]),'ELSE':([46,53,],[52,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmts':([0,45,],[2,50,]),'stmt':([0,2,45,50,],[3,11,3,11,]),'type':([0,2,45,50,],[4,4,4,4,]),'expr':([13,14,15,16,18,21,33,36,38,],[20,27,29,29,31,34,41,44,47,]),'args_opt':([14,],[24,]),'args_list':([14,],[25,]),'empty':([14,45,],[26,51,]),'condition':([15,16,],[28,30,]),'block':([37,39,52,],[46,48,54,]),'stmts_opt':([45,],[49,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmts','program',1,'p_program','main.py',405),
  ('stmts_opt -> stmts','stmts_opt',1,'p_stmts_opt','main.py',409),
  ('stmts_opt -> empty','stmts_opt',1,'p_stmts_opt','main.py',410),
  ('stmts -> stmts stmt','stmts',2,'p_stmts_multi','main.py',414),
  ('stmts -> stmt','stmts',1,'p_stmts_one','main.py',418),
  ('stmt -> type ID PUNTOCOMA','stmt',3,'p_stmt_decl','main.py',422),
  ('stmt -> type ID ASIGNACION expr PUNTOCOMA','stmt',5,'p_stmt_decl_assign','main.py',427),
  ('stmt -> ID ASIGNACION expr PUNTOCOMA','stmt',4,'p_stmt_assign','main.py',432),
  ('stmt -> PRINT PARENTESIS args_opt PARENTESIS PUNTOCOMA','stmt',5,'p_stmt_print_multi','main.py',437),
  ('args_opt -> args_list','args_opt',1,'p_args_opt','main.py',442),
  ('args_opt -> empty','args_opt',1,'p_args_opt','main.py',443),
  ('args_list -> expr','args_list',1,'p_args_list_single','main.py',448),
  ('args_list -> args_list COMA expr','args_list',3,'p_args_list_many','main.py',452),
  ('stmt -> IF PARENTESIS condition PARENTESIS block','stmt',5,'p_stmt_if_no_else','main.py',457),
  ('stmt -> IF PARENTESIS condition PARENTESIS block ELSE block','stmt',7,'p_stmt_if_with_else','main.py',462),
  ('stmt -> WHILE PARENTESIS condition PARENTESIS block','stmt',5,'p_stmt_while','main.py',467),
  ('type -> INT','type',1,'p_type_int','main.py',472),
  ('type -> FLOAT','type',1,'p_type_float','main.py',476),
  ('block -> PARENTESIS stmts_opt PARENTESIS','block',3,'p_block','main.py',481),
  ('condition -> expr COMPARACION expr','condition',3,'p_condition_gt','main.py',486),
  ('expr -> expr OPERACION expr','expr',3,'p_expr_binop','main.py',491),
  ('expr -> PARENTESIS expr PARENTESIS','expr',3,'p_expr_group','main.py',496),
  ('expr -> ID','expr',1,'p_expr_id','main.py',500),
  ('expr -> NUMERO','expr',1,'p_expr_num','main.py',504),
  ('expr -> DESC','expr',1,'p_expr_desc','main.py',508),
  ('empty -> <empty>','empty',0,'p_empty','main.py',512),
]
